server:
  port: 8082

eureka:
  instance:
    hostname: client-eureka-provider
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: client-eureka-provider
#  zipkin:
#    base-url: http://192.168.2.120:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1.0  # ²ÉÑùÂÊ

management:
  endpoints:
    web:
      exposure:
        include: "*"