server:
  port: 8888

eureka:
  instance:
    hostname: demo-config-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: demo-config-server
  rabbitmq:
    host: 192.168.2.120
    port: 5672
    username: guest
    password: guest
  cloud:
    client:
      hostname: demo-config-server
    config:
      label: master
      monitor:
        endpoint:
          path: /config
      server:
        prefix: /config
        encrypt:
          enabled: false
        monitor:
          github:
            enabled: true
        git:
          uri: http://gitlab.tenxcloud.com/microservice/configproject.git
          cloneOnStart: true
          username: springcloudconfig
          password: Passw0rd
          basedir: target/configs
          accessToken: AvX1ypxSG2G4Zdi14BGk

encrypt:
  key: tenxcloud-configserver-encrypt-key

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
